// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8aVb-mtMpqMyQWBJSbtQeSxYTc_tD3I',
    appId: '1:884075996015:web:6a0a4af3661aa1f69b7e9a',
    messagingSenderId: '884075996015',
    projectId: 'flutter-concepts-3f302',
    authDomain: 'flutter-concepts-3f302.firebaseapp.com',
    storageBucket: 'flutter-concepts-3f302.firebasestorage.app',
    measurementId: 'G-EE7E5GHJ1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9aX3IziNXZ3Rl9kdmHs7gOUXxDyf5kPo',
    appId: '1:884075996015:android:b42cae65d92645419b7e9a',
    messagingSenderId: '884075996015',
    projectId: 'flutter-concepts-3f302',
    storageBucket: 'flutter-concepts-3f302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKkvxZPzKFfR1suf8DB6P5vnXfCwJDuKo',
    appId: '1:884075996015:ios:997a973199dab09c9b7e9a',
    messagingSenderId: '884075996015',
    projectId: 'flutter-concepts-3f302',
    storageBucket: 'flutter-concepts-3f302.firebasestorage.app',
    iosBundleId: 'com.example.flutterConcepts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKkvxZPzKFfR1suf8DB6P5vnXfCwJDuKo',
    appId: '1:884075996015:ios:997a973199dab09c9b7e9a',
    messagingSenderId: '884075996015',
    projectId: 'flutter-concepts-3f302',
    storageBucket: 'flutter-concepts-3f302.firebasestorage.app',
    iosBundleId: 'com.example.flutterConcepts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY8aVb-mtMpqMyQWBJSbtQeSxYTc_tD3I',
    appId: '1:884075996015:web:1f001041079889da9b7e9a',
    messagingSenderId: '884075996015',
    projectId: 'flutter-concepts-3f302',
    authDomain: 'flutter-concepts-3f302.firebaseapp.com',
    storageBucket: 'flutter-concepts-3f302.firebasestorage.app',
    measurementId: 'G-PJWZJFSNFC',
  );
}
